# This is a basic workflow to help you get started with Actions

name: Context Info

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches-ignore: main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
runs:
  using: 'composite'
  # Steps represent a sequence of tasks that will be executed as part of the job
  steps:
    - run: echo "$GITHUB_CONTEXT"
      shell: bash
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}


